# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.7-dev

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/xraylarch
    - export PATH="$HOME/xraylarch/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels gsecars
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n xlarch python=3.7 numpy scipy matplotlib sqlalchemy requests pandas scikit-image scikit-learn h5py wxpython yaml pyyaml pip
    - source activate xlarch
    - pip install dill nose peakutils pillow psutil psycopg2 pyepics pytest silx sphinx termcolor xraydb lmfit asteval pycifrw
    - conda install -c gsecars dioptas pyfai tomopy uncertainties wxutils wxmplot patchelf pango pcre
    - pip install pyshortcuts==1.5
    - python setup.py install
    - conda list

script:
    - cd tests
    - pytest
