name: MacOS, Conda Python 3.10 through 3.13

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python from Miniconda/conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniconda-version: latest
          channels: conda-forge
          channel-priority: strict
          activate-environment: anaconda-client-env
          python-version: ${{ matrix.python-version }}
      - name: Install conda dependencies
        run: |
          printenv
          conda install -y -c conda-forge python=${{ matrix.python-version }} "numpy>=2.0" "scipy>=1.15" "matplotlib>=3.9" "h5py>=3.10" "wxpython>=4.2" scikit-learn jupyter pytest pytest-cov coverage codecov plotly bokeh  pymatgen==2025.6.14  mp-api>=0.45.6  emmet-core>=0.84.9 setuptools pip
          conda list
          which conda
          conda activate base
      - name: Install xraylarch and other dependencies with pip
        run: |
          conda activate base
          which python
          python -m pip install wxmplot
          python -m pip install larixite
          python -m pip install ".[larix]"
      - name: Run test suite
        run: |
          cd tests
          sh run_tests.sh
